# Basic
title: LL86
subtitle: A blog-orientation theme for Jekyll
welcome_message: <a href="https://github.com/LL86/vno-jekyll" target="_blank">Download the theme</a>
description: Vno Jekyll is a port of my Ghost theme vno.
creator: <a href="https://ll86.github.io/">@LL86</a>

url: "https://ll86.github.io/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://project.LL86.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: 
    github: https://github.com/LL86/LL86.github.io/commits/master
    twitter: 
    gplus: 107108267983477358170
    mail:  shilianlian86@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
